package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/liforra/warp/internal/sshconfig"
)

// runConvert implements `warp --convert --config=<ssh_config> --output=<warp.toml>`.
// It's a one-time materialization of the same ssh_config parsing that
// [sources.ssh_config] does automatically at load time -- useful when you'd
// rather have real, editable [host.X] blocks in warp.toml than rely on
// auto-sourcing, or just want a starting point to edit from.
func runConvert() error {
	source := configPath
	if source == "" {
		source = "~/.ssh/config"
	}

	hosts, err := sshconfig.Parse(source)
	if err != nil {
		return fmt.Errorf("reading %q: %w", source, err)
	}

	text := renderWarpToml(source, hosts)

	if outputPath == "" {
		fmt.Print(text)
		return nil
	}

	if _, err := os.Stat(outputPath); err == nil {
		return fmt.Errorf("%s already exists; remove it or choose a different --output", outputPath)
	}
	if err := os.WriteFile(outputPath, []byte(text), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}
	fmt.Printf("wrote %d host(s) to %s\n", len(hosts), outputPath)
	return nil
}

// renderWarpToml builds a warp.toml document with one [host.X] block per
// sshconfig.Host. protocol is set explicitly to "ssh", since that's the one
// thing confirmed by the source file -- mosh/et/tailscale/tsh support is
// unknown, so nothing is guessed at.
func renderWarpToml(source string, hosts []sshconfig.Host) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by `warp --convert --config=%s`\n", source)
	fmt.Fprintf(&b, "# %d host(s) imported. Review before use -- protocol is set to\n", len(hosts))
	b.WriteString("# \"ssh\" for all of them since that's the one thing this file confirms;\n")
	b.WriteString("# add mosh/et/tailscale/tsh/telnet to the chain, or other options, as needed.\n\n")

	if len(hosts) == 0 {
		b.WriteString("# No literal (non-wildcard) Host blocks were found to import.\n")
		return b.String()
	}

	for _, h := range hosts {
		fmt.Fprintf(&b, "[host.%s]\n", tomlBareOrQuoted(h.Name))
		fmt.Fprintf(&b, "addresses = %s\n", tomlQuote(firstNonEmptyStr(h.HostName, h.Name)))
		b.WriteString("protocol = \"ssh\"\n")
		if h.User != "" {
			fmt.Fprintf(&b, "user = %s\n", tomlQuote(h.User))
		}
		if h.Port != 0 {
			fmt.Fprintf(&b, "port = %d\n", h.Port)
		}
		if h.IdentityFile != "" {
			fmt.Fprintf(&b, "identity_file = %s\n", tomlQuote(h.IdentityFile))
		}
		if h.ProxyJump != "" {
			fmt.Fprintf(&b, "\n[host.%s.ssh]\n", tomlBareOrQuoted(h.Name))
			fmt.Fprintf(&b, "proxy_jump = %s\n", tomlQuote(h.ProxyJump))
		}
		b.WriteString("\n")
	}

	return strings.TrimRight(b.String(), "\n") + "\n"
}

func firstNonEmptyStr(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

// tomlBareOrQuoted renders a TOML table key, quoting it if it's not a bare
// key (TOML bare keys are limited to [A-Za-z0-9_-]).
func tomlBareOrQuoted(s string) string {
	for _, r := range s {
		if !(r == '_' || r == '-' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return strconv.Quote(s)
		}
	}
	return s
}

func tomlQuote(s string) string {
	return strconv.Quote(s)
}
